### ISSUE TITLE
Dasturni o'rnatish uchun installer (MSI) package.

### ISSUE THREAD

**Issue by KOMILJONOV** [osmon-lang/osmon#93]
### Is there an existing issue/discussion for your proposal?

- [X] I have searched existing issues and discussions

### Description

Dasturni zip file ni ichiga qo'yib qo'ysangiz ko'pchilik ishlatolmasligi mumkin.

Shuning uchun dasturni o'rnatish uchun installer (MSI yoki alohida .exe) file ishlab chiqish kerak.

Shunda ko'pchilik ishlatishiga oson bo'ladi.

### Motivation

Agar yordam kerak bo'lsa: https://t.me/komiljonov_dev

**Comment by katsuki-yuri** [comment]
Yaxshi fikr, inobatga olaman!

**Comment by katsuki-yuri** [comment]
Windows support chiqarilib yuborilishi bilan birgalikda o'rnatuvchilarga ehtiyoj yo'qoldi. Shu bilan birgalikda GUI installer dastur o'rniga CLI o'rnatish uslubi hozirchalik asosiy qilib olingan. Balkim LLVM ga o'tsak kelajakda GUI installer haqida ham o'ylab ko'rarmiz.

https://github.com/osmon-lang/dunyo/tree/main/apps/web/public/install
